[project]
name = "07-batch-processing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.12"
dependencies = [
    "ipykernel>=7.2.0",
    "pandas>=3.0.1",
    "pyspark>=4.1.1",
]
